#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0
import sys
from math import gcd

def fmul(b,n,d):
    return ((1 << b) * n + d - 1) // d

def fadj(b,n,d):
    d //= gcd(n,d)
    return ((1 << b) * (d - 1)) // d

def fmuls(b,n,d):
    s = 0
    while True:
        if fmul(s,n,d) >= (1 << (b - 1)):
            return s
        s += 1

def emit(hz):
    out = []
    out.append("/* Automatically generated by kernel/time/timeconst.bc */\n")
    out.append(f"/* Time conversion constants for HZ == {hz} */\n\n")
    out.append("#ifndef KERNEL_TIMECONST_H\n#define KERNEL_TIMECONST_H\n\n")
    out.append("#include <linux/param.h>\n#include <linux/types.h>\n\n")
    out.append(f"#if HZ != {hz}\n")
    out.append('#error "include/generated/timeconst.h has the wrong HZ value!"\n')
    out.append("#endif\n\n")
    if hz < 2:
        out.append("#error Totally bogus HZ value!\n")
        return ''.join(out)

    hx = lambda v: format(v, 'X')

    s = fmuls(32, 1000, hz)
    out.append(f"#define HZ_TO_MSEC_MUL32\tU64_C(0x{hx(fmul(s,1000,hz))})\n")
    out.append(f"#define HZ_TO_MSEC_ADJ32\tU64_C(0x{hx(fadj(s,1000,hz))})\n")
    out.append(f"#define HZ_TO_MSEC_SHR32\t{s}\n")

    s = fmuls(32, hz, 1000)
    out.append(f"#define MSEC_TO_HZ_MUL32\tU64_C(0x{hx(fmul(s,hz,1000))})\n")
    out.append(f"#define MSEC_TO_HZ_ADJ32\tU64_C(0x{hx(fadj(s,hz,1000))})\n")
    out.append(f"#define MSEC_TO_HZ_SHR32\t{s}\n")

    cd = gcd(hz,1000)
    out.append(f"#define HZ_TO_MSEC_NUM\t\t{1000//cd}\n")
    out.append(f"#define HZ_TO_MSEC_DEN\t\t{hz//cd}\n")
    out.append(f"#define MSEC_TO_HZ_NUM\t\t{hz//cd}\n")
    out.append(f"#define MSEC_TO_HZ_DEN\t\t{1000//cd}\n\n")

    s = fmuls(32, 1000000, hz)
    out.append(f"#define HZ_TO_USEC_MUL32\tU64_C(0x{hx(fmul(s,1000000,hz))})\n")
    out.append(f"#define HZ_TO_USEC_ADJ32\tU64_C(0x{hx(fadj(s,1000000,hz))})\n")
    out.append(f"#define HZ_TO_USEC_SHR32\t{s}\n")

    s = fmuls(32, hz, 1000000)
    out.append(f"#define USEC_TO_HZ_MUL32\tU64_C(0x{hx(fmul(s,hz,1000000))})\n")
    out.append(f"#define USEC_TO_HZ_ADJ32\tU64_C(0x{hx(fadj(s,hz,1000000))})\n")
    out.append(f"#define USEC_TO_HZ_SHR32\t{s}\n")

    cd = gcd(hz,1000000)
    out.append(f"#define HZ_TO_USEC_NUM\t\t{1000000//cd}\n")
    out.append(f"#define HZ_TO_USEC_DEN\t\t{hz//cd}\n")
    out.append(f"#define USEC_TO_HZ_NUM\t\t{hz//cd}\n")
    out.append(f"#define USEC_TO_HZ_DEN\t\t{1000000//cd}\n")

    cd = gcd(hz,1000000000)
    out.append(f"#define HZ_TO_NSEC_NUM\t\t{1000000000//cd}\n")
    out.append(f"#define HZ_TO_NSEC_DEN\t\t{hz//cd}\n")
    out.append(f"#define NSEC_TO_HZ_NUM\t\t{hz//cd}\n")
    out.append(f"#define NSEC_TO_HZ_DEN\t\t{1000000000//cd}\n\n")
    out.append("#endif /* KERNEL_TIMECONST_H */\n")
    return ''.join(out)

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print('usage: gen_timeconst.py <HZ>', file=sys.stderr)
        sys.exit(1)
    hz = int(sys.argv[1])
    sys.stdout.write(emit(hz))
